version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      # Changed from /var/lib/postgresql/data to /var/lib/postgresql
      - postgres_data:/var/lib/postgresql
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  redis:
    image: docker.io/library/redis:8
    container_name: redis-cache
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  redis_data: